### PR TITLE
Fixing squid: S1213 Members of an interface or class should appear in a pre-defined order

### PR DESCRIPTION
**Pull request by devFozgul**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1213 - “Members of an interface or class should appear in a pre-defined order”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1213
 Please let me know if you have any questions.
Fevzi Ozgul

### CODE REVIEW

**Comment by devFozgul** [comment]
I do not see any problems in the changes I made. I wonder why it says "the branch has conflicts" This PR is about changing the place of the variables within the class. Nothing more, nothing less. It should not result in any conflicts.

**Comment by dounine** [comment]
I put this RP first off, you can try to send a RP

**Comment by devFozgul** [comment]
Hi dounine,
Do you mean I should send the Pull Request again?

**Comment by dounine** [comment]
yes

**Comment by dounine** [comment]
i close this pr

**Comment by devFozgul** [comment]
I created a new one.

**Pull request closed without merging**
